# Generated by Django 4.1.2 on 2023-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_explainability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='.'),
        ),
    ]
