# Generated by Django 4.0.6 on 2023-03-13 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('superuser', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('ai_method', models.CharField(max_length=255)),
                ('bayesian_optimization', models.CharField(default='no', max_length=255)),
                ('train_test_validation_split', models.CharField(max_length=255)),
                ('sampling_technique', models.CharField(blank=True, max_length=255, null=True)),
                ('train_set', models.FileField(upload_to='final_table/')),
                ('test_set', models.FileField(upload_to='final_table/')),
                ('company_id', models.FileField(default=('Company_ID,Column1,Column2\n',), upload_to='final_table/')),
                ('validation_set', models.FileField(blank=True, null=True, upload_to='final_table/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='XGModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('superuser', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('ai_method', models.CharField(max_length=100)),
                ('train_test_validation_split', models.CharField(max_length=100)),
                ('sampling_technique', models.CharField(blank=True, max_length=100, null=True)),
                ('bayesian_optimization', models.CharField(default='no', max_length=255)),
                ('model_file', models.FileField(upload_to='xg_model/')),
                ('train_x_set', models.FileField(upload_to='xg_sets/')),
                ('train_y_set', models.FileField(upload_to='xg_sets/')),
                ('test_x_set', models.FileField(upload_to='xg_sets/')),
                ('test_y_set', models.FileField(upload_to='xg_sets/')),
                ('best_params', models.TextField(blank=True, null=True)),
                ('trials', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
