# Generated by Django 4.1.2 on 2023-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('superuser', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('file_1', models.FileField(blank=True, upload_to='group_split/')),
                ('file_2', models.FileField(blank=True, upload_to='group_split/')),
                ('file_3', models.FileField(blank=True, upload_to='group_split/')),
                ('file_4', models.FileField(blank=True, upload_to='group_split/')),
            ],
        ),
    ]
