# Generated by Django 4.1.2 on 2023-01-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_representation', '0002_groupsplit_file_name_alter_groupsplit_file_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsplit',
            name='file_1',
        ),
        migrations.RemoveField(
            model_name='groupsplit',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='groupsplit',
            name='file_3',
        ),
        migrations.RemoveField(
            model_name='groupsplit',
            name='file_4',
        ),
        migrations.AddField(
            model_name='groupsplit',
            name='file',
            field=models.FileField(default='test', upload_to='group_split/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupsplit',
            name='group_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
