# Generated by Django 4.1.2 on 2023-02-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_representation', '0003_remove_groupsplit_file_1_remove_groupsplit_file_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsplit',
            name='ai_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupsplit',
            name='sampling_technique',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupsplit',
            name='train_test_validation_split',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
