# Generated by Django 4.1.2 on 2023-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_representation', '0004_groupsplit_ai_method_groupsplit_sampling_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsplit',
            name='ai_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='groupsplit',
            name='sampling_technique',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='groupsplit',
            name='train_test_validation_split',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
