# Generated by Django 4.1.2 on 2023-02-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_representation', '0005_alter_groupsplit_ai_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsplit',
            name='bayesian_optimization',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
    ]
