# Generated by Django 4.1.2 on 2023-02-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_representation', '0006_groupsplit_bayesian_optimization'),
    ]

    operations = [
    ]
