# Generated by Django 4.1.2 on 2023-02-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_representation', '0007_auto_20230220_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsplit',
            name='sampling_technique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
