# Generated by Django 4.1.2 on 2023-01-28 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_number',
            new_name='group_choice',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='group',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
