# Generated by Django 4.1.2 on 2023-01-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_preprocessing', '0002_rename_group_number_group_group_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='file_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
